title: Annie Meeder
description: | 
  PhD Student & NSF Fellow
  University of Colorado Boulder
  annie.meeder@colorado.edu
logo: anniemeeder.github.io/sciflowers.png

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
