title: Annie Meeder
<img width="528" alt="Screen Shot 2023-08-30 at 3 07 28 PM" src="https://github.com/annieM459/anniemeeder.github.io/assets/140002702/255ba5dd-d86e-42b5-b85b-dd85690058f8">
annie.meeder@colorado.edu
description: PhD Student & NSF Fellow
University of Colorado Boulder
annie.meeder@colorado.edu

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
